# Autocut Configuration File
# This file defines the cron delay and shortcuts for the autocut application

# Cron delay in cron format (e.g., "*/5 * * * *" for every 5 minutes)

# List of shortcuts to be processed
shortcuts:
  - displayName: "Update Focus Mode HA"
    shortcutName: "FocusMode"
    shortcutInput: {}
    cronDelay: "*/1 * * * *"
    delay: 0
    description: "Gets the current active status by name and syncs it to HA"
    enabled: true